"""Add bsn_number to User

Revision ID: 0a4ec5c5609d
Revises: df528c6ddffd
Create Date: 2026-03-17 12:05:04.413684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a4ec5c5609d'
down_revision = 'df528c6ddffd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bsn_number', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_learning_progress', schema=None) as batch_op:
        batch_op.alter_column('learning_path_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('user_item_mastery', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_item_mastery_item_id'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('last_result',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('consecutive_correct_sessions',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('total_correct',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('total_attempts',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_member_id'))
        batch_op.alter_column('learning_map_tour_completed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('profile_public',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'1'"))
        batch_op.alter_column('deleted_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
        batch_op.drop_column('bsn_number')

    with op.batch_alter_table('registration_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('form_data', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('error_message', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('field', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('error_code', sa.VARCHAR(length=100), nullable=True))

    with op.batch_alter_table('page_views', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('learning_path', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('incoming_emails', schema=None) as batch_op:
        batch_op.alter_column('source_account',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'info'"))

    with op.batch_alter_table('forum_topics', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('big_domain', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('code',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###
