"""Add DigiD authentication support

Revision ID: 246641da327c
Revises: 1f9e56f5f447
Create Date: 2025-07-07 12:21:30.214783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '246641da327c'
down_revision = '1f9e56f5f447'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('digid_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('bsn', sa.String(length=9), nullable=False),
    sa.Column('digid_username', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_used', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('digid_session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_digid_session_session_id'), ['session_id'], unique=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('digid_username', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('bsn', sa.String(length=9), nullable=True))
        batch_op.add_column(sa.Column('digid_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('created_via_digid', sa.Boolean(), nullable=True))
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_user_bsn'), ['bsn'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_digid_username'), ['digid_username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_digid_username'))
        batch_op.drop_index(batch_op.f('ix_user_bsn'))
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
        batch_op.drop_column('created_via_digid')
        batch_op.drop_column('digid_verified')
        batch_op.drop_column('bsn')
        batch_op.drop_column('digid_username')

    with op.batch_alter_table('digid_session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_digid_session_session_id'))

    op.drop_table('digid_session')
    # ### end Alembic commands ###
