"""Add Invitation model for user invitation system

Revision ID: 496c010bf6c2
Revises: a6d3bd99490c
Create Date: 2025-09-19 08:59:19.977706

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '496c010bf6c2'
down_revision = 'a6d3bd99490c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_templates')
    op.drop_table('_alembic_tmp_learning_path')
    op.drop_table('email_campaign')
    with op.batch_alter_table('learning_path', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('user_learning_progress', schema=None) as batch_op:
        batch_op.alter_column('learning_path_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_learning_progress', schema=None) as batch_op:
        batch_op.alter_column('learning_path_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('learning_path', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               autoincrement=True)

    op.create_table('email_campaign',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('admin_user_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('template_id', sa.INTEGER(), nullable=False),
    sa.Column('target_criteria', sa.TEXT(), nullable=True),
    sa.Column('target_count', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('scheduled_at', sa.DATETIME(), nullable=True),
    sa.Column('started_at', sa.DATETIME(), nullable=True),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.Column('sent_count', sa.INTEGER(), nullable=True),
    sa.Column('delivered_count', sa.INTEGER(), nullable=True),
    sa.Column('opened_count', sa.INTEGER(), nullable=True),
    sa.Column('clicked_count', sa.INTEGER(), nullable=True),
    sa.Column('bounced_count', sa.INTEGER(), nullable=True),
    sa.Column('unsubscribed_count', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['admin_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['email_template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('_alembic_tmp_learning_path',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('name_nl', sa.VARCHAR(length=200), nullable=True),
    sa.Column('name_ru', sa.VARCHAR(length=200), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('exam_component', sa.VARCHAR(length=20), nullable=False),
    sa.Column('exam_weight', sa.FLOAT(), nullable=False),
    sa.Column('exam_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('duration_weeks', sa.INTEGER(), nullable=True),
    sa.Column('total_estimated_hours', sa.INTEGER(), nullable=True),
    sa.Column('prerequisites', sqlite.JSON(), nullable=True),
    sa.Column('modules', sqlite.JSON(), nullable=True),
    sa.Column('assessment', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('(TRUE)'), nullable=True),
    sa.Column('irt_difficulty_range', sqlite.JSON(), nullable=True),
    sa.Column('irt_discrimination_range', sqlite.JSON(), nullable=True),
    sa.Column('target_ability_levels', sqlite.JSON(), nullable=True),
    sa.Column('adaptive_routing', sqlite.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_templates',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('subject', sa.VARCHAR(length=500), nullable=False),
    sa.Column('message', sa.TEXT(), nullable=False),
    sa.Column('email_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('action_url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('action_text', sa.VARCHAR(length=255), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('usage_count', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
