"""Add membership fields to User model

Revision ID: 52664ae226ef
Revises: 496c010bf6c2
Create Date: 2025-10-02 11:40:27.981629

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '52664ae226ef'
down_revision = '496c010bf6c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_learning_path')
    with op.batch_alter_table('forum_topics', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['deleted_by'], ['id'])

    with op.batch_alter_table('incoming_emails', schema=None) as batch_op:
        batch_op.alter_column('source_account',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'info'"))

    with op.batch_alter_table('learning_path', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('page_views', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user_sessions', ['session_id'], ['session_id'])

    with op.batch_alter_table('registration_logs', schema=None) as batch_op:
        batch_op.drop_column('form_data')
        batch_op.drop_column('error_message')
        batch_op.drop_column('error_code')
        batch_op.drop_column('field')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_member_id'), ['member_id'], unique=True)

    with op.batch_alter_table('user_learning_progress', schema=None) as batch_op:
        batch_op.alter_column('learning_path_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_learning_progress', schema=None) as batch_op:
        batch_op.alter_column('learning_path_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_member_id'))

    with op.batch_alter_table('registration_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('field', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('error_code', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('error_message', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('form_data', sa.TEXT(), nullable=True))

    with op.batch_alter_table('page_views', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('learning_path', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('incoming_emails', schema=None) as batch_op:
        batch_op.alter_column('source_account',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'info'"))

    with op.batch_alter_table('forum_topics', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    op.create_table('_alembic_tmp_learning_path',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('name_nl', sa.VARCHAR(length=200), nullable=True),
    sa.Column('name_ru', sa.VARCHAR(length=200), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('exam_component', sa.VARCHAR(length=20), nullable=False),
    sa.Column('exam_weight', sa.FLOAT(), nullable=False),
    sa.Column('exam_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('duration_weeks', sa.INTEGER(), nullable=True),
    sa.Column('total_estimated_hours', sa.INTEGER(), nullable=True),
    sa.Column('prerequisites', sqlite.JSON(), nullable=True),
    sa.Column('modules', sqlite.JSON(), nullable=True),
    sa.Column('assessment', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('(TRUE)'), nullable=True),
    sa.Column('irt_difficulty_range', sqlite.JSON(), nullable=True),
    sa.Column('irt_discrimination_range', sqlite.JSON(), nullable=True),
    sa.Column('target_ability_levels', sqlite.JSON(), nullable=True),
    sa.Column('adaptive_routing', sqlite.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
