"""Make user_id nullable in DiagnosticSession

Revision ID: 56151235de91
Revises: 72ce5ce7eeb1
Create Date: 2025-07-18 14:58:31.242089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56151235de91'
down_revision = '72ce5ce7eeb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diagnostic_session', schema=None) as batch_op:
        batch_op.drop_index('ix_diagnostic_session_user_id')

    with op.batch_alter_table('personal_learning_plan', schema=None) as batch_op:
        batch_op.drop_index('ix_personal_learning_plan_user_id')

    with op.batch_alter_table('study_session', schema=None) as batch_op:
        batch_op.drop_index('ix_study_session_learning_plan_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_session', schema=None) as batch_op:
        batch_op.create_index('ix_study_session_learning_plan_id', ['learning_plan_id'], unique=False)

    with op.batch_alter_table('personal_learning_plan', schema=None) as batch_op:
        batch_op.create_index('ix_personal_learning_plan_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('diagnostic_session', schema=None) as batch_op:
        batch_op.create_index('ix_diagnostic_session_user_id', ['user_id'], unique=False)

    # ### end Alembic commands ###
