"""Add country_code field for phone numbers

Revision ID: 635a383d760b
Revises: c0cb184bb4f2
Create Date: 2025-09-08 22:20:45.417148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '635a383d760b'
down_revision = 'c0cb184bb4f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country_code', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('country_code')

    # ### end Alembic commands ###
