"""add english reading models

Revision ID: 66cd825725a2
Revises: add_profile_public
Create Date: 2025-11-04 01:15:41.985770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66cd825725a2'
down_revision = 'add_profile_public'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop temporary table if it exists
    from sqlalchemy import inspect
    inspector = inspect(op.get_bind())
    tables = inspector.get_table_names()
    
    if '_alembic_tmp_big_domain' in tables:
        op.drop_table('_alembic_tmp_big_domain')
    
    # Create English Reading tables if they don't exist
    if 'english_passages' not in tables:
        op.create_table('english_passages',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=200), nullable=False),
        sa.Column('text', sa.Text(), nullable=False),
        sa.Column('category', sa.String(length=100), nullable=True),
        sa.Column('difficulty', sa.Integer(), nullable=True),
        sa.Column('word_count', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
    
    if 'english_questions' not in tables:
        op.create_table('english_questions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('passage_id', sa.Integer(), nullable=False),
        sa.Column('question_number', sa.Integer(), nullable=True),
        sa.Column('question_type', sa.String(length=50), nullable=True),
        sa.Column('question_text', sa.Text(), nullable=False),
        sa.Column('correct_answer', sa.String(length=500), nullable=True),
        sa.Column('options', sa.Text(), nullable=True),
        sa.Column('explanation', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['passage_id'], ['english_passages.id'], name='fk_english_questions_passage_id'),
        sa.PrimaryKeyConstraint('id')
        )
    
    if 'user_english_progress' not in tables:
        op.create_table('user_english_progress',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('passage_id', sa.Integer(), nullable=False),
        sa.Column('completed_at', sa.DateTime(), nullable=True),
        sa.Column('score', sa.Integer(), nullable=True),
        sa.Column('total_questions', sa.Integer(), nullable=True),
        sa.Column('time_spent', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['passage_id'], ['english_passages.id'], name='fk_user_english_progress_passage_id'),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_user_english_progress_user_id'),
        sa.PrimaryKeyConstraint('id')
        )
    
    with op.batch_alter_table('big_domain', schema=None) as batch_op:
        batch_op.alter_column('code',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.create_foreign_key('fk_big_domain_category_id', 'domain_category', ['category_id'], ['id'])

    with op.batch_alter_table('forum_topics', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_forum_topics_deleted_by', 'user', ['deleted_by'], ['id'])

    # Check if incoming_emails table exists and has source_account column
    if 'incoming_emails' in tables:
        inspector = inspect(op.get_bind())
        columns = [col['name'] for col in inspector.get_columns('incoming_emails')]
        
        if 'source_account' in columns:
            # Column exists, just alter it
            with op.batch_alter_table('incoming_emails', schema=None) as batch_op:
                batch_op.alter_column('source_account',
                       existing_type=sa.VARCHAR(length=50),
                       nullable=False,
                       existing_server_default=sa.text("'info'"))
        else:
            # Column doesn't exist, add it
            with op.batch_alter_table('incoming_emails', schema=None) as batch_op:
                batch_op.add_column(sa.Column('source_account', sa.String(length=50), nullable=False, server_default='info'))

    with op.batch_alter_table('learning_path', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('page_views', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_page_views_session_id', 'user_sessions', ['session_id'], ['session_id'])

    with op.batch_alter_table('registration_logs', schema=None) as batch_op:
        batch_op.drop_column('form_data')
        batch_op.drop_column('field')
        batch_op.drop_column('error_message')
        batch_op.drop_column('error_code')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('deleted_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('profile_public',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'1'"))
        batch_op.create_index(batch_op.f('ix_user_member_id'), ['member_id'], unique=True)

    with op.batch_alter_table('user_learning_progress', schema=None) as batch_op:
        batch_op.alter_column('learning_path_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_learning_progress', schema=None) as batch_op:
        batch_op.alter_column('learning_path_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_member_id'))
        batch_op.alter_column('profile_public',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'1'"))
        batch_op.alter_column('deleted_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)

    with op.batch_alter_table('registration_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('error_code', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('error_message', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('field', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('form_data', sa.TEXT(), nullable=True))

    with op.batch_alter_table('page_views', schema=None) as batch_op:
        batch_op.drop_constraint('fk_page_views_session_id', type_='foreignkey')

    with op.batch_alter_table('learning_path', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               autoincrement=True)

    # Check if incoming_emails table exists and has source_account column
    from sqlalchemy import inspect
    inspector = inspect(op.get_bind())
    tables = inspector.get_table_names()
    
    if 'incoming_emails' in tables:
        columns = [col['name'] for col in inspector.get_columns('incoming_emails')]
        
        if 'source_account' in columns:
            with op.batch_alter_table('incoming_emails', schema=None) as batch_op:
                batch_op.alter_column('source_account',
                       existing_type=sa.VARCHAR(length=50),
                       nullable=True,
                       existing_server_default=sa.text("'info'"))

    with op.batch_alter_table('forum_topics', schema=None) as batch_op:
        batch_op.drop_constraint('fk_forum_topics_deleted_by', type_='foreignkey')

    with op.batch_alter_table('big_domain', schema=None) as batch_op:
        batch_op.drop_constraint('fk_big_domain_category_id', type_='foreignkey')
        batch_op.alter_column('code',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    op.create_table('_alembic_tmp_big_domain',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('code', sa.VARCHAR(length=50), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('weight_percentage', sa.FLOAT(), nullable=False),
    sa.Column('order', sa.INTEGER(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('category', sa.VARCHAR(length=50), nullable=True),
    sa.Column('exam_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('is_critical', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True),
    sa.Column('subcategories', sa.TEXT(), nullable=True),
    sa.Column('historical_questions', sa.BOOLEAN(), server_default=sa.text('1'), nullable=True),
    sa.Column('open_book', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True),
    sa.Column('category_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['domain_category.id'], name='fk_big_domain_category_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    
    # Drop English Reading tables
    op.drop_table('user_english_progress')
    op.drop_table('english_questions')
    op.drop_table('english_passages')
    
    # ### end Alembic commands ###
