"""Add missing fields to DiagnosticSession

Revision ID: 72ce5ce7eeb1
Revises: 3939cbd3ba11
Create Date: 2025-07-18 14:54:42.660361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72ce5ce7eeb1'
down_revision = '3939cbd3ba11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diagnostic_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_question_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ip_address', sa.String(length=45), nullable=True))
        batch_op.create_foreign_key('fk_diagnostic_session_current_question', 'question', ['current_question_id'], ['id'])

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_question_big_domain', 'big_domain', ['big_domain_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_constraint('fk_question_big_domain', type_='foreignkey')

    with op.batch_alter_table('diagnostic_session', schema=None) as batch_op:
        batch_op.drop_constraint('fk_diagnostic_session_current_question', type_='foreignkey')
        batch_op.drop_column('ip_address')
        batch_op.drop_column('current_question_id')

    # ### end Alembic commands ###
