"""Add IRT feedback fields to StudySession and PersonalLearningPlan

Revision ID: 75e4cf77facb
Revises: 8d0c012429c2
Create Date: 2025-08-08 02:00:33.484485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75e4cf77facb'
down_revision = '8d0c012429c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_ability_before', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('session_ability_after', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ability_change', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ability_confidence', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('version', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_ability_update', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('ability_updated', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('feedback_processed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_session', schema=None) as batch_op:
        batch_op.drop_column('feedback_processed')
        batch_op.drop_column('ability_updated')
        batch_op.drop_column('last_ability_update')
        batch_op.drop_column('version')
        batch_op.drop_column('ability_confidence')
        batch_op.drop_column('ability_change')
        batch_op.drop_column('session_ability_after')
        batch_op.drop_column('session_ability_before')

    # ### end Alembic commands ###
