"""Add DomainCategory model

Revision ID: 855f7a693107
Revises: 52664ae226ef
Create Date: 2025-10-25 00:10:21.595896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '855f7a693107'
down_revision = '52664ae226ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domain_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_nl', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('profession', sa.String(length=50), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domain_category_profession'), 'domain_category', ['profession'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_domain_category_profession'), table_name='domain_category')
    op.drop_table('domain_category')
    # ### end Alembic commands ###
