"""Add category_id to BIGDomain

Revision ID: 8b2f6eda6f2e
Revises: 855f7a693107
Create Date: 2025-10-25 00:10:27.818918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b2f6eda6f2e'
down_revision = '855f7a693107'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('big_domain', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.create_index('ix_big_domain_category_id', ['category_id'], unique=False)
        batch_op.create_foreign_key('fk_big_domain_category_id', 'domain_category', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('big_domain', schema=None) as batch_op:
        batch_op.drop_constraint('fk_big_domain_category_id', type_='foreignkey')
        batch_op.drop_index('ix_big_domain_category_id')
        batch_op.drop_column('category_id')
    # ### end Alembic commands ###
