"""Add profession field to Question model

Revision ID: add_profession_question_001
Revises: a037f7cd2416
Create Date: 2025-01-29 15:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_profession_question_001'
down_revision = 'a037f7cd2416'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profession', sa.String(length=50), nullable=True))
        batch_op.create_index('ix_questions_profession', ['profession'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_index('ix_questions_profession')
        batch_op.drop_column('profession')
    # ### end Alembic commands ###







