"""Add SpacedRepetitionItem model

Revision ID: spaced_repetition_001
Revises: 61b8e1269fad
Create Date: 2024-01-15 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'spaced_repetition_001'
down_revision = '61b8e1269fad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spaced_repetition_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('ease_factor', sa.Float(), nullable=True),
    sa.Column('interval', sa.Integer(), nullable=True),
    sa.Column('repetitions', sa.Integer(), nullable=True),
    sa.Column('quality', sa.Integer(), nullable=True),
    sa.Column('average_quality', sa.Float(), nullable=True),
    sa.Column('next_review', sa.DateTime(), nullable=False),
    sa.Column('last_review', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('domain', sa.String(length=50), nullable=True),
    sa.Column('total_reviews', sa.Integer(), nullable=True),
    sa.Column('consecutive_correct', sa.Integer(), nullable=True),
    sa.Column('consecutive_incorrect', sa.Integer(), nullable=True),
    sa.Column('irt_difficulty', sa.Float(), nullable=True),
    sa.Column('user_ability', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'question_id', name='_user_question_sr_uc')
    )
    op.create_index(op.f('ix_spaced_repetition_item_domain'), 'spaced_repetition_item', ['domain'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_spaced_repetition_item_domain'), table_name='spaced_repetition_item')
    op.drop_table('spaced_repetition_item')
    # ### end Alembic commands ### 