"""Add password reset fields to User model

Revision ID: b33ed38533b3
Revises: 635a383d760b
Create Date: 2025-09-09 09:22:32.886834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b33ed38533b3'
down_revision = '635a383d760b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_reset_token', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('password_reset_sent_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_password_reset_token'), ['password_reset_token'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_password_reset_token'))
        batch_op.drop_column('password_reset_sent_at')
        batch_op.drop_column('password_reset_token')

    # ### end Alembic commands ###
