"""Add missing profile_photo field to User model

Revision ID: bfcebd2de498
Revises: c6e107e8deb9
Create Date: 2025-07-08 16:59:37.387518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfcebd2de498'
down_revision = 'c6e107e8deb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_photo', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('birth_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('big_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('workplace', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('specialization', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('registration_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('license_expiry', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('additional_documents', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('language_certificates', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('notification_settings', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('privacy_settings', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('profile_updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('profile_updated_at')
        batch_op.drop_column('privacy_settings')
        batch_op.drop_column('notification_settings')
        batch_op.drop_column('language_certificates')
        batch_op.drop_column('additional_documents')
        batch_op.drop_column('license_expiry')
        batch_op.drop_column('registration_date')
        batch_op.drop_column('specialization')
        batch_op.drop_column('workplace')
        batch_op.drop_column('big_number')
        batch_op.drop_column('gender')
        batch_op.drop_column('birth_date')
        batch_op.drop_column('phone')
        batch_op.drop_column('profile_photo')

    # ### end Alembic commands ###
