"""Update registration form: remove BIG fields, add other fields and new consent structure

Revision ID: c0cb184bb4f2
Revises: c93fed74995f
Create Date: 2025-09-08 22:07:29.872562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0cb184bb4f2'
down_revision = 'c93fed74995f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('other_profession', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('other_nationality', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('other_legal_status', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('required_consents', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('optional_consents', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('digital_signature', sa.String(length=255), nullable=True))
        batch_op.drop_column('license_expiry')
        batch_op.drop_column('big_number')
        batch_op.drop_column('registration_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registration_date', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('big_number', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('license_expiry', sa.DATE(), nullable=True))
        batch_op.drop_column('digital_signature')
        batch_op.drop_column('optional_consents')
        batch_op.drop_column('required_consents')
        batch_op.drop_column('other_legal_status')
        batch_op.drop_column('other_nationality')
        batch_op.drop_column('other_profession')

    # ### end Alembic commands ###
