"""Add program interests and motivation fields to User model

Revision ID: c63605ada651
Revises: e3d05159dd76
Create Date: 2025-09-14 19:26:34.068918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c63605ada651'
down_revision = 'e3d05159dd76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('program_interests', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('motivation', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('program_notifications', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('program_notifications')
        batch_op.drop_column('motivation')
        batch_op.drop_column('program_interests')

    # ### end Alembic commands ###
