"""Add registration fields to User model

Revision ID: c6e107e8deb9
Revises: 78cf4ad8fcf3
Create Date: 2025-07-08 01:43:34.448228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6e107e8deb9'
down_revision = '78cf4ad8fcf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registration_completed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('profession', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('diploma_file', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('language_certificate', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('language_certificate')
        batch_op.drop_column('diploma_file')
        batch_op.drop_column('profession')
        batch_op.drop_column('registration_completed')

    # ### end Alembic commands ###
