"""Add email confirmation fields to User model

Revision ID: c93fed74995f
Revises: 75e4cf77facb
Create Date: 2025-09-08 17:52:23.125063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c93fed74995f'
down_revision = '75e4cf77facb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_confirmed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('email_confirmation_token', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('email_confirmation_sent_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('nationality', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('legal_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('dutch_level', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('english_level', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('idw_assessment', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('big_exam_registered', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('exam_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('preparation_time', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('diploma_info', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('work_experience', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('additional_qualifications', sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_email_confirmation_token'), ['email_confirmation_token'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email_confirmation_token'))
        batch_op.drop_column('additional_qualifications')
        batch_op.drop_column('work_experience')
        batch_op.drop_column('diploma_info')
        batch_op.drop_column('preparation_time')
        batch_op.drop_column('exam_date')
        batch_op.drop_column('big_exam_registered')
        batch_op.drop_column('idw_assessment')
        batch_op.drop_column('english_level')
        batch_op.drop_column('dutch_level')
        batch_op.drop_column('legal_status')
        batch_op.drop_column('nationality')
        batch_op.drop_column('email_confirmation_sent_at')
        batch_op.drop_column('email_confirmation_token')
        batch_op.drop_column('email_confirmed')

    # ### end Alembic commands ###
