"""Add IRT integration improvements

Revision ID: d4129d49b4ba
Revises: 0d36785d9566
Create Date: 2025-08-05 01:32:27.929128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4129d49b4ba'
down_revision = '0d36785d9566'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: Most indexes and constraints already exist, skipping to avoid conflicts
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: Most indexes and constraints should remain, skipping to avoid conflicts
    pass
    # ### end Alembic commands ###
