"""Add structured education fields to User model

Revision ID: e3d05159dd76
Revises: b33ed38533b3
Create Date: 2025-09-11 16:46:54.559421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3d05159dd76'
down_revision = 'b33ed38533b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('university_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('degree_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('study_start_year', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('study_end_year', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('study_country', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('medical_specialization', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('additional_education_info', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('additional_education_info')
        batch_op.drop_column('medical_specialization')
        batch_op.drop_column('study_country')
        batch_op.drop_column('study_end_year')
        batch_op.drop_column('study_start_year')
        batch_op.drop_column('degree_type')
        batch_op.drop_column('university_name')

    # ### end Alembic commands ###
