"""add daily assignments model

Revision ID: eadf0bc80aff
Revises: 66cd825725a2
Create Date: 2025-11-04 10:04:55.786736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eadf0bc80aff'
down_revision = '66cd825725a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create daily_assignments table (if it doesn't exist)
    try:
        op.create_table('daily_assignments',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('user_id', sa.Integer(), nullable=False),
            sa.Column('assignment_date', sa.Date(), nullable=False),
            sa.Column('assignment_type', sa.String(length=20), nullable=False),
            sa.Column('item_ids', sa.Text(), nullable=False),
            sa.Column('completed', sa.Boolean(), nullable=True),
            sa.Column('completed_at', sa.DateTime(), nullable=True),
            sa.Column('attempts', sa.Integer(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.Column('updated_at', sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_daily_assignments_user_id', ondelete='CASCADE'),
            sa.PrimaryKeyConstraint('id', name='pk_daily_assignments'),
            sa.UniqueConstraint('user_id', 'assignment_date', 'assignment_type', name='_user_date_type_uc')
        )
        op.create_index(op.f('ix_daily_assignments_assignment_date'), 'daily_assignments', ['assignment_date'], unique=False)
        op.create_index(op.f('ix_daily_assignments_assignment_type'), 'daily_assignments', ['assignment_type'], unique=False)
    except Exception:
        # Table might already exist, skip
        pass
    
    # Удаляем временную таблицу, если она существует
    try:
        op.drop_table('_alembic_tmp_big_domain')
    except Exception:
        # Таблица может не существовать, игнорируем ошибку
        pass
    
    with op.batch_alter_table('big_domain', schema=None) as batch_op:
        batch_op.alter_column('code',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.create_foreign_key('fk_big_domain_category_id', 'domain_category', ['category_id'], ['id'])

    with op.batch_alter_table('forum_topics', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['deleted_by'], ['id'])

    with op.batch_alter_table('incoming_emails', schema=None) as batch_op:
        batch_op.alter_column('source_account',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'info'"))

    with op.batch_alter_table('learning_path', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('page_views', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user_sessions', ['session_id'], ['session_id'])

    with op.batch_alter_table('registration_logs', schema=None) as batch_op:
        batch_op.drop_column('field')
        batch_op.drop_column('error_message')
        batch_op.drop_column('form_data')
        batch_op.drop_column('error_code')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('deleted_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('profile_public',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'1'"))
        batch_op.create_index(batch_op.f('ix_user_member_id'), ['member_id'], unique=True)

    with op.batch_alter_table('user_learning_progress', schema=None) as batch_op:
        batch_op.alter_column('learning_path_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop daily_assignments table
    op.drop_index(op.f('ix_daily_assignments_assignment_type'), table_name='daily_assignments')
    op.drop_index(op.f('ix_daily_assignments_assignment_date'), table_name='daily_assignments')
    op.drop_table('daily_assignments')
    
    with op.batch_alter_table('user_learning_progress', schema=None) as batch_op:
        batch_op.alter_column('learning_path_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_member_id'))
        batch_op.alter_column('profile_public',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'1'"))
        batch_op.alter_column('deleted_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)

    with op.batch_alter_table('registration_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('error_code', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('form_data', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('error_message', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('field', sa.VARCHAR(length=100), nullable=True))

    with op.batch_alter_table('page_views', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('learning_path', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('incoming_emails', schema=None) as batch_op:
        batch_op.alter_column('source_account',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'info'"))

    with op.batch_alter_table('forum_topics', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('big_domain', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('code',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    op.create_table('_alembic_tmp_big_domain',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('code', sa.VARCHAR(length=50), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('weight_percentage', sa.FLOAT(), nullable=False),
    sa.Column('order', sa.INTEGER(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('category', sa.VARCHAR(length=50), nullable=True),
    sa.Column('exam_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('is_critical', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True),
    sa.Column('subcategories', sa.TEXT(), nullable=True),
    sa.Column('historical_questions', sa.BOOLEAN(), server_default=sa.text('1'), nullable=True),
    sa.Column('open_book', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True),
    sa.Column('category_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['domain_category.id'], name='fk_big_domain_category_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###
