"""ensure_subject_order_column

Revision ID: 2ff97374f815
Revises: 2aae3b85715b
Create Date: 2025-07-11 10:47:22.110610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ff97374f815'
down_revision = '2aae3b85715b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order', sa.Integer(), nullable=True))
        batch_op.drop_index('ix_subject_slug')
        batch_op.drop_column('is_premium')
        batch_op.drop_column('emoji')
        batch_op.drop_column('slug')
        batch_op.drop_column('order_index')
        batch_op.drop_column('color')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.VARCHAR(length=7), nullable=True))
        batch_op.add_column(sa.Column('order_index', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('slug', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('emoji', sa.VARCHAR(length=10), nullable=True))
        batch_op.add_column(sa.Column('is_premium', sa.BOOLEAN(), server_default=sa.text("'false'"), nullable=True))
        batch_op.create_index('ix_subject_slug', ['slug'], unique=1)
        batch_op.drop_column('order')

    # ### end Alembic commands ###
