"""Add RAG system models

Revision ID: 357d4ff0e5be
Revises: 
Create Date: 2025-06-05 15:11:18.957587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '357d4ff0e5be'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('learning_path', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               existing_server_default=sa.text('1'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('learning_path', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('1'))

    # ### end Alembic commands ###
