"""Initial migration

Revision ID: initial_migration
Revises: 
Create Date: 2025-06-17 11:41:24.032000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'initial_migration'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # Таблица уже создана вручную, поэтому здесь ничего не делаем
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ### 